#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        systemctl stop vaprs.service 2>/dev/null || true
        systemctl disable vaprs.service 2>/dev/null || true
        ;;
    upgrade)
        systemctl stop vaprs.service 2>/dev/null || true
        ;;
esac

exit 0
